import Script from "next/script";
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";

// Importing CSS files
import "./css/all.min.css";
import "./css/animate.css";
import "./css/bootstrap.min.css";
import "./css/custom_spacing.css";
import "./css/responsive.css";
import "./css/select2.min.css";
import "./css/slick.css";
import "./css/venobox.min.css";
import "./css/style.css";
import Footer from "./Components/Shared/Footer";
import Navbar from "./Components/Shared/Navbar";
import Header from "./Components/pageSections/Home/Header";
import "./globals.css";
import { AOSProvider } from "@/lib/aos";

// Metadata configuration
export const metadata = {
  title: "Medico Tech",
  description: "Generated by Medico Tech",
};

export default function RootLayout({
  children,
}) {
  return (
    <html lang="en">
      <body className="geistSans-variable geistMono-variable">
        {/* Load JavaScript files with `next/script` */}
        <Script src="/js/Font-Awesome.js" strategy="lazyOnload" />
        <Script src="/js/main.js" strategy="lazyOnload" />
        <Script src="/js/sticky_sidebar.js" strategy="lazyOnload" />
        <Script src="/js/bootstrap.bundle.min.js" strategy="lazyOnload" />
        <Script src="/js/wow.min.js" strategy="lazyOnload" />
        <Script src="/js/venobox.min.js" strategy="lazyOnload" />
        <Script src="/js/slick.min.js" strategy="lazyOnload" />
        <Script src="/js/select2.min.js" strategy="lazyOnload" />
        <Script src="/js/jquery.waypoints.min.js" strategy="lazyOnload" />
        <Script src="/js/jquery-3.7.0.min.js" strategy="lazyOnload" />
        <Script src="/js/jquery.countup.min.js" strategy="lazyOnload" />
        <Script
          src="https://code.jquery.com/jquery-3.6.0.min.js"
          strategy="beforeInteractive"
        />
        <div className="max-width-screen overflow-x-hidden">

          <Header />
          <Navbar />
          <AOSProvider>
            {children}
          </AOSProvider>
          <Footer />
          <ToastContainer />
        </div>
      </body>
    </html>
  );
}
